name: Pipeline of the Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      HEADLESS: "true"
    steps:
      - name: Checkout of the repository
        uses: actions/checkout@v4  

      - name: Python configurations
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Clean pip cache
        run: |
          pip cache purge

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Finishing the Chrome process (if exists)
        run: |
          pkill -9 chrome || true
          ps aux | grep chrome    

      - name: Run the tests
        run: |
          pytest --html=report.html
      
      - name: Upload of the html HTML repost as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-bdd-report-html
          path: report.html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: "screenshots/*.png"